apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-docker-exporter
  namespace: default
spec:
  endpoints:
    - interval: 5s
      path: /actuator/prometheus
      port: test-docker-service
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: test-docker-service